from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class WorkbenchLibraryContractTests(unittest.TestCase):
    def read(self, name: str) -> str:
        return (ROOT / name).read_text(encoding="utf-8")

    def test_both_localized_workbenches_load_the_shared_library(self) -> None:
        for name, language in [
            ("garfield_gas_workbench_pro.html", "zh-CN"),
            ("garfield_gas_workbench_pro_english.html", "en"),
        ]:
            html = self.read(name)
            self.assertIn(f'<html lang="{language}">', html)
            self.assertIn("window.GarfieldWorkbenchBridge", html)
            self.assertIn('src="assets/js/gas-search-core.js"', html)
            self.assertIn('src="assets/js/workbench-library.js"', html)
            self.assertIn('src="assets/js/gas-file-parser.js"', html)
            self.assertIn("GarfieldGasParser.parse", html)
            self.assertNotIn("function parseLevels", html)
            self.assertNotIn("const FLOAT_RE", html)
            self.assertIn("sourceSha256", html)
            self.assertIn("sourcePath", html)
            self.assertIn("file.arrayBuffer()", html)

    def test_generated_standalone_workbenches_have_no_external_dependencies(self) -> None:
        for name, language in [
            ("garfield_workbench_offline_zh.html", "zh-CN"),
            ("garfield_workbench_offline_en.html", "en"),
        ]:
            html = self.read(name)
            self.assertIn(f'<html lang="{language}">', html)
            self.assertIn("Generated by tools/build_standalone_workbenches.py", html)
            for dependency in [
                "assets/js/gas-file-parser.js",
                "assets/js/gas-search-core.js",
                "assets/js/workbench-library.js",
            ]:
                self.assertIn(f'data-inlined-source="{dependency}"', html)
                self.assertNotIn(f'<script src="{dependency}"></script>', html)
            self.assertIn('id="fileInput" type="file" multiple', html)
            self.assertIn("root.GarfieldGasParser=api", html)
            self.assertIn("window.GasSearchCore", html)
            self.assertIn("localOnly:", html)

    def test_root_and_legacy_entry_points_preserve_public_navigation(self) -> None:
        root_entry = self.read("index.html")
        self.assertIn("garfield_gas_workbench_pro.html", root_entry)
        self.assertIn("garfield_gas_workbench_pro_english.html", root_entry)
        legacy_entry = self.read("garfield_gas_multi_file_viewer_advanced_legend.html")
        legacy_path = "legacy/garfield_gas_multi_file_viewer_advanced_legend.html"
        self.assertIn(legacy_path, legacy_entry)
        self.assertTrue((ROOT / legacy_path).is_file())

    def test_shared_parser_supports_record_extensions(self) -> None:
        script = self.read("assets/js/gas-file-parser.js")
        self.assertIn("root.GarfieldGasParser=api", script)
        self.assertIn("module.exports=api", script)
        self.assertIn("extraValuesPerRecord=extraValues/recordCount", script)
        self.assertIn("q=recordStart+actualRecordSize", script)
        self.assertIn("extensionValues", script)

    def test_library_limits_remote_paths_and_verifies_content(self) -> None:
        script = self.read("assets/js/workbench-library.js")
        self.assertIn("file.path.startsWith('GasFile/')", script)
        self.assertIn("file.path.includes('..')", script)
        self.assertIn("url.origin!==location.origin", script)
        self.assertIn("crypto.subtle.digest('SHA-256'", script)
        self.assertIn("response.arrayBuffer()", script)
        self.assertIn("200*1024*1024", script)
        self.assertIn("AbortController", script)
        self.assertIn('id="gasLibraryExactSet" type="checkbox">', script)
        self.assertNotIn('id="gasLibraryExactSet" type="checkbox" checked', script)

    def test_transport_parameters_can_drive_the_x_axis(self) -> None:
        for name in [
            "garfield_gas_workbench_pro.html",
            "garfield_gas_workbench_pro_english.html",
        ]:
            html = self.read(name)
            self.assertEqual(html.count('id="pointOrder"'), 1)
            self.assertEqual(html.count('id="showXErrors"'), 1)
            self.assertIn("appendParamGroup($('xSelect')", html)
            self.assertIn("parametric?'sourceEoverP':'x'", html)
            self.assertIn("xErr:parametric?getErr", html)
            self.assertIn("nearestByX(item.points,x)", html)
            self.assertIn("'source_E_V_cm'", html)
            self.assertIn("'source_E_over_P'", html)
            self.assertIn("'pointOrder','showErrors','showXErrors'", html)

    def test_identifier_composition_is_authoritative_for_legend_and_scans(self) -> None:
        fixture = self.read(
            "GasFile/RPCgas_Typical/Different_GasFraction/"
            "c2h2f4_ic4h10_sf6_90_5_5.gas"
        )
        self.assertIn(
            "Identifier: C2H2F4 90%, iC4H10 5%, SF6 5%",
            fixture,
        )
        for name in [
            "garfield_gas_workbench_pro.html",
            "garfield_gas_workbench_pro_english.html",
        ]:
            html = self.read(name)
            self.assertIn("function canonicalGasName(name)", html)
            self.assertIn("/^i-?c4h10$/i.test(name)?'i-C4H10':name", html)
            self.assertIn(
                "return Object.keys(identifier).length?identifier:arrayComposition(g)",
                html,
            )
            self.assertNotIn(
                "return{...arrayComposition(g),...identifierComposition(g)}",
                html,
            )

    def test_standalone_search_uses_shared_core_and_links_both_workbenches(self) -> None:
        html = self.read("gas_file_search.html")
        self.assertIn('src="assets/js/gas-search-core.js"', html)
        self.assertIn("searchCore.evaluate", html)
        self.assertIn("searchCore.sortResults", html)
        self.assertIn("garfield_gas_workbench_pro_english.html?gas=", html)
        self.assertIn("garfield_gas_workbench_pro.html?gas=", html)
        self.assertIn('id="exactComponents" type="checkbox">', html)
        self.assertNotIn('id="exactComponents" type="checkbox" checked', html)
        self.assertIn("url.searchParams.set('exactSet',query.exactSet?'1':'0')", html)
        self.assertIn("el('exactComponents').checked=false", html)


if __name__ == "__main__":
    unittest.main()
